queue_rules:
  - name: default
    batch_size: 8
    checks_timeout: 10800 s
    merge_method: squash
    queue_conditions:
      - "#approved-reviews-by >= 1"
      - base = unstable
      - label = ready-for-bors
      - check-success = license/cla,target-branch-check
    merge_conditions:
      - check-success = release-tests-ubuntu,release-tests-windows,beacon-chain-tests,op-pool-tests,network-tests,slasher-tests,debug-tests-ubuntu,state-transition-vectors-ubuntu,ef-tests-ubuntu,dockerfile-ubuntu,eth1-simulator-ubuntu,merge-transition-ubuntu,no-eth1-simulator-ubuntu,syncing-simulator-ubuntu,doppelganger-protection-test,execution-engine-integration-ubuntu,check-code,check-msrv,cargo-udeps,compile-with-beta-compiler