# Test that local testnet starts successfully.
name: local testnet

on:
  push:
    branches:
      - unstable
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-local-testnet:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install -y kurtosis-cli yq
          kurtosis analytics disable

      - name: Start local testnet
        run: ./start_local_testnet.sh -c && sleep 60
        working-directory: scripts/local_testnet

      - name: Print logs
        run: kurtosis enclave dump local-testnet logs-local-testnet
        working-directory: scripts/local_testnet

      - name: Stop local testnet
        run: kurtosis enclave rm -f local-testnet
        working-directory: scripts/local_testnet

      - name: Start local testnet with blinded block production
        run: ./start_local_testnet.sh -c -p -b false && sleep 60
        working-directory: scripts/local_testnet

      - name: Print logs for blinded block testnet
        run: kurtosis enclave dump local-testnet logs-blinded-block-testnet
        working-directory: scripts/local_testnet

      - name: Stop local testnet with blinded block production
        run: kurtosis enclave rm -f local-testnet
        working-directory: scripts/local_testnet

      - name: Upload logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: local-testnet-logs
          path: |
            scripts/local_testnet/logs-local-testnet
            scripts/local_testnet/logs-blinded-block-testnet
          retention-days: 3

  # This job succeeds ONLY IF all others succeed. It is used by the merge queue to determine whether
  # a PR is safe to merge. New jobs should be added here.
  local-testnet-success:
    name: local-testnet-success
    runs-on: ubuntu-latest
    needs: ["run-local-testnet"]
    steps:
      - uses: actions/checkout@v4
      - name: Check that success job is dependent on all others
        run: ./scripts/ci/check-success-job.sh ./.github/workflows/local-testnet.yml local-testnet-success
