# Test that local testnet starts successfully.
name: local testnet

on:
  push:
    branches:
      - unstable
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-local-testnet:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
    runs-on: ${{ matrix.os }}
    env:
      # Enable portable to prevent issues with caching `blst` for the wrong CPU type
      FEATURES: portable,jemalloc
    steps:
      - name: empty step
        run: echo "pass"

  # This job succeeds ONLY IF all others succeed. It is used by the merge queue to determine whether
  # a PR is safe to merge. New jobs should be added here.
  local-testnet-success:
    name: local-testnet-success
    runs-on: ubuntu-latest
    needs: ["run-local-testnet"]
    steps:
      - name: empty step
        run: echo "pass"
