name: test-suite

on:
  push:
    branches:
      - stable
      - staging
      - trying
      - 'pr/*'
  pull_request:
  merge_group:
env:
  # Deny warnings in CI
  # Disable debug info (see https://github.com/sigp/lighthouse/issues/4005)
  RUSTFLAGS: "-D warnings -C debuginfo=0"
  # The Nightly version used for cargo-udeps, might need updating from time to time.
  PINNED_NIGHTLY: nightly-2023-04-16
  # Prevent Github API rate limiting.
  LIGHTHOUSE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Enable self-hosted runners for the sigp repo only.
  SELF_HOSTED_RUNNERS: ${{ github.repository == 'sigp/lighthouse' }}
  # Self-hosted runners need to reference a different host for `./watch` tests.
  WATCH_HOST: ${{ github.repository == 'sigp/lighthouse' && 'host.docker.internal' || 'localhost' }}
jobs:
  release-tests-ubuntu:
    name: release-tests-ubuntu
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "large"]') || 'ubuntu-latest'  }}
    env:
      RUST_BACKTRACE: 1
    steps:
    - uses: actions/checkout@v3
    - name: Get latest version of stable Rust
      if: env.SELF_HOSTED_RUNNERS == false
      run: rustup update stable
    - name: Install Protoc
      uses: arduino/setup-protoc@e52d9eb8f7b63115df1ac544a1376fdbf5a39612
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Foundry (anvil)
      uses: foundry-rs/foundry-toolchain@v1
    - name: Run tests in release
      run: make test-release
  release-tests-windows:
    name: release-tests-windows
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "windows"]') || 'windows-2019'  }}
    env:
      RUST_BACKTRACE: 1
    steps:
    - uses: actions/checkout@v3
    - name: Get latest version of stable Rust
      if: env.SELF_HOSTED_RUNNERS == false
      run: rustup update stable
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install windows build tools
      run: |
        choco install python protoc visualstudio2019-workload-vctools -y
        npm config set msvs_version 2019
    - name: Install Foundry (anvil)
      uses: foundry-rs/foundry-toolchain@v1
    - name: Install make
      run: choco install -y make
    - uses: KyleMayes/install-llvm-action@v1
      if: env.SELF_HOSTED_RUNNERS == false
      with:
        version: "15.0"
        directory: ${{ runner.temp }}/llvm
    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
    - name: Run tests in release
      run: make test-release
  beacon-chain-tests:
    name: beacon-chain-tests
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "large"]') || 'ubuntu-latest'  }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v3
      - name: Get latest version of stable Rust
        if: env.SELF_HOSTED_RUNNERS == false
        run: rustup update stable
      - name: Install Protoc
        uses: arduino/setup-protoc@e52d9eb8f7b63115df1ac544a1376fdbf5a39612
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run beacon_chain tests for all known forks
        run: make test-beacon-chain
  debug-tests-ubuntu:
    name: debug-tests-ubuntu
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "large"]') || 'ubuntu-latest'  }}
    env:
      RUST_BACKTRACE: 1
    steps:
    - uses: actions/checkout@v3
    - name: Get latest version of stable Rust
      if: env.SELF_HOSTED_RUNNERS == false
      run: rustup update stable
    - name: Install Protoc
      uses: arduino/setup-protoc@e52d9eb8f7b63115df1ac544a1376fdbf5a39612
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Foundry (anvil)
      uses: foundry-rs/foundry-toolchain@v1
    - name: Run tests in debug
      run: make test-debug
  ef-tests-ubuntu:
    name: ef-tests-ubuntu
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "small"]') || 'ubuntu-latest'  }}
    steps:
      - uses: actions/checkout@v3
      - name: Get latest version of stable Rust
        if: env.SELF_HOSTED_RUNNERS == false
        run: rustup update stable
      - name: Install Protoc
        uses: arduino/setup-protoc@e52d9eb8f7b63115df1ac544a1376fdbf5a39612
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run consensus-spec-tests with blst, milagro and fake_crypto
        run: make test-ef
