name: test-suite

on:
  push:
    branches:
      - stable
      - staging
      - trying
      - 'pr/*'
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Deny warnings in CI
  # Disable debug info (see https://github.com/sigp/lighthouse/issues/4005)
  RUSTFLAGS: "-D warnings -C debuginfo=0"
  # Prevent Github API rate limiting.
  LIGHTHOUSE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Enable self-hosted runners for the sigp repo only.
  SELF_HOSTED_RUNNERS: ${{ github.repository == 'sigp/lighthouse' }}
  # Self-hosted runners need to reference a different host for `./watch` tests.
  WATCH_HOST: ${{ github.repository == 'sigp/lighthouse' && 'host.docker.internal' || 'localhost' }}
  # Disable incremental compilation
  CARGO_INCREMENTAL: 0
  # Enable portable to prevent issues with caching `blst` for the wrong CPU type
  TEST_FEATURES: portable
jobs:
  target-branch-check:
    name: target-branch-check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    steps:
      - name: pass
        run: echo "success"
  release-tests-ubuntu:
    name: release-tests-ubuntu
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "large"]') || 'ubuntu-latest'  }}
    steps:
      - name: pass
        run: echo "success"
  release-tests-windows:
    name: release-tests-windows
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "windows", "CI"]') || 'windows-2019'  }}
    steps:
      - name: pass
        run: echo "success"
  beacon-chain-tests:
    name: beacon-chain-tests
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "large"]') || 'ubuntu-latest'  }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: pass
        run: echo "success"
  op-pool-tests:
    name: op-pool-tests
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: pass
        run: exit 1 #fail
  network-tests:
    name: network-tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: pass
        run: echo "success"
  slasher-tests:
    name: slasher-tests
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: pass
        run: echo "success"
  debug-tests-ubuntu:
    name: debug-tests-ubuntu
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "large"]') || 'ubuntu-latest'  }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: pass
        run: echo "success"
  state-transition-vectors-ubuntu:
    name: state-transition-vectors-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: echo "success"
  ef-tests-ubuntu:
    name: ef-tests-ubuntu
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "small"]') || 'ubuntu-latest'  }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: pass
        run: echo "success"
  dockerfile-ubuntu:
    name: dockerfile-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: echo "success"
  eth1-simulator-ubuntu:
    name: eth1-simulator-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: echo "success"
  merge-transition-ubuntu:
    name: merge-transition-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: pass
      run: echo "success"
  no-eth1-simulator-ubuntu:
    name: no-eth1-simulator-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: echo "success"
  syncing-simulator-ubuntu:
    name: syncing-simulator-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: echo "success"
  doppelganger-protection-test:
    name: doppelganger-protection-test
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "small"]') || 'ubuntu-latest'  }}
    env:
      # Enable portable to prevent issues with caching `blst` for the wrong CPU type
      FEATURES: jemalloc,portable
    steps:
      - name: pass
        run: echo "success"
  execution-engine-integration-ubuntu:
    name: execution-engine-integration-ubuntu
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "small"]') || 'ubuntu-latest'  }}
    steps:
      - name: pass
        run: echo "success"
  check-code:
    name: check-code
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1
    steps:
      - name: pass
        run: echo "success"
  check-msrv:
    name: check-msrv
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: echo "success"
  cargo-udeps:
    name: cargo-udeps
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: echo "success"
    env:
      # Allow warnings on Nightly
      RUSTFLAGS: ""
  compile-with-beta-compiler:
    name: compile-with-beta-compiler
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: echo "success"
