name: test-suite

on:
  push:
    branches:
      - stable
      - staging
      - trying
      - 'pr/*'
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Deny warnings in CI
  # Disable debug info (see https://github.com/sigp/lighthouse/issues/4005)
  RUSTFLAGS: "-D warnings -C debuginfo=0"
  # Prevent Github API rate limiting.
  LIGHTHOUSE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Enable self-hosted runners for the sigp repo only.
  SELF_HOSTED_RUNNERS: ${{ github.repository == 'sigp/lighthouse' }}
  # Self-hosted runners need to reference a different host for `./watch` tests.
  WATCH_HOST: ${{ github.repository == 'sigp/lighthouse' && 'host.docker.internal' || 'localhost' }}
  # Disable incremental compilation
  CARGO_INCREMENTAL: 0
  # Enable portable to prevent issues with caching `blst` for the wrong CPU type
  TEST_FEATURES: portable
jobs:
  target-branch-check:
    name: target-branch-check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    steps:
    - name: empty step
      run: echo "pass"
  release-tests-ubuntu:
    name: release-tests-ubuntu
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "large"]') || 'ubuntu-latest'  }}
    steps:
    - name: empty step
      run: echo "pass"
  release-tests-windows:
    name: release-tests-windows
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "windows", "CI"]') || 'windows-2019'  }}
    steps:
    - name: empty step
      run: echo "pass"
  beacon-chain-tests:
    name: beacon-chain-tests
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "large"]') || 'ubuntu-latest'  }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: empty step
      run: echo "pass"
  op-pool-tests:
    name: op-pool-tests
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: empty step
      run: echo "pass"
  network-tests:
    name: network-tests
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: empty step
      run: echo "pass"
  slasher-tests:
    name: slasher-tests
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: empty step
      run: echo "pass"
  debug-tests-ubuntu:
    name: debug-tests-ubuntu
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "large"]') || 'ubuntu-latest'  }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: empty step
      run: echo "pass"
  state-transition-vectors-ubuntu:
    name: state-transition-vectors-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: empty step
      run: echo "pass"
  ef-tests-ubuntu:
    name: ef-tests-ubuntu
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "small"]') || 'ubuntu-latest'  }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: empty step
      run: echo "pass"
  dockerfile-ubuntu:
    name: dockerfile-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: empty step
      run: echo "pass"
  eth1-simulator-ubuntu:
    name: eth1-simulator-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: empty step
      run: echo "pass"
  merge-transition-ubuntu:
    name: merge-transition-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: empty step
      run: echo "pass"
  no-eth1-simulator-ubuntu:
    name: no-eth1-simulator-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: empty step
      run: echo "pass"
  syncing-simulator-ubuntu:
    name: syncing-simulator-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: empty step
      run: echo "pass"
  doppelganger-protection-test:
    name: doppelganger-protection-test
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "small"]') || 'ubuntu-latest'  }}
    env:
      # Enable portable to prevent issues with caching `blst` for the wrong CPU type
      FEATURES: jemalloc,portable
    steps:
    - name: empty step
      run: echo "pass"
  execution-engine-integration-ubuntu:
    name: execution-engine-integration-ubuntu
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "CI", "small"]') || 'ubuntu-latest'  }}
    steps:
    - name: empty step
      run: echo "pass"
  check-code:
    name: check-code
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1
    steps:
    - name: empty step
      run: echo "pass"
  check-msrv:
    name: check-msrv
    runs-on: ubuntu-latest
    steps:
    - name: empty step
      run: echo "pass"
  cargo-udeps:
    name: cargo-udeps
    runs-on: ubuntu-latest
    steps:
    - name: empty step
      run: echo "pass"
  compile-with-beta-compiler:
    name: compile-with-beta-compiler
    runs-on: ubuntu-latest
    steps:
    - name: empty step
      run: echo "pass"
  cli-check:
    name: cli-check
    runs-on: ubuntu-latest
    steps:
    - name: empty step
      run: echo "pass"
  test-suite-success:
    name: test-suite-success
    runs-on: ubuntu-latest
    needs: [
      'target-branch-check',
      'release-tests-ubuntu',
      'release-tests-windows',
      'beacon-chain-tests',
      'op-pool-tests',
      'network-tests',
      'slasher-tests',
      'debug-tests-ubuntu',
      'state-transition-vectors-ubuntu',
      'ef-tests-ubuntu',
      'dockerfile-ubuntu',
      'eth1-simulator-ubuntu',
      'merge-transition-ubuntu',
      'no-eth1-simulator-ubuntu',
      'syncing-simulator-ubuntu',
      'doppelganger-protection-test',
      'execution-engine-integration-ubuntu',
      'check-code',
      'check-msrv',
      'cargo-udeps',
      'compile-with-beta-compiler',
      'cli-check',
    ]
    steps:
      - uses: actions/checkout@v3
      - name: Check that success job is dependent on all others
        run: ./scripts/ci/check-success-job.sh ./.github/workflows/test-suite.yml test-suite-success
