name: test-suite

on:
  push:
    branches:
      - stable
      - staging
      - trying
      - 'pr/*'
  pull_request:
  merge_group:
env:
  # Deny warnings in CI
  # Disable debug info (see https://github.com/sigp/lighthouse/issues/4005)
  RUSTFLAGS: "-D warnings -C debuginfo=0"
  # The Nightly version used for cargo-udeps, might need updating from time to time.
  PINNED_NIGHTLY: nightly-2023-04-16
  # Prevent Github API rate limiting.
  LIGHTHOUSE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Enable self-hosted runners for the sigp repo only.
  SELF_HOSTED_RUNNERS: ${{ github.repository == 'sigp/lighthouse' }}
  # Self-hosted runners need to reference a different host for `./watch` tests.
  WATCH_HOST: ${{ github.repository == 'sigp/lighthouse' && 'host.docker.internal' || 'localhost' }}
jobs:
  debug-tests-ubuntu:
    name: debug-tests-ubuntu
    # Use self-hosted runners only on the sigp repo.
    runs-on: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "large"]') || 'ubuntu-latest'  }}
    steps:
    - uses: actions/checkout@v3
    - name: Get latest version of stable Rust
      if: env.SELF_HOSTED_RUNNERS == false
      run: rustup update stable
    - name: Install Protoc
      uses: arduino/setup-protoc@e52d9eb8f7b63115df1ac544a1376fdbf5a39612
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Foundry (anvil)
      uses: foundry-rs/foundry-toolchain@v1
    - name: Run tests in debug
      run: make test-debug
